In [1]:
import ioh
import numpy as np
import modcma
import random as r

In [2]:
f = ioh.get_problem(fid=2, instance=1, dimension=5, problem_type=ioh.ProblemType.BBOB)

In [3]:
f.state

<State evaluations: 0 optimum_found: false current_best: <Solution x: [nan, nan, nan, nan, nan] y: inf>>

In [4]:
# initial_pop = np.array([r.uniform(f.bounds.lb[0], f.bounds.ub[0]) for _ in range(len(f.bounds.lb)*10)]).reshape((5, 10))
initial_pop = np.float64(np.random.uniform(f.bounds.lb[0], f.bounds.ub[0], (f.meta_data.n_variables, 1)))

In [5]:
initial_pop

array([[ 1.65295784],
       [-4.17532663],
       [-4.29109666],
       [-0.56129481],
       [-2.83043699]])

In [6]:
# random_search(f_3_10, budget=10)
params = modcma.Parameters(d=f.meta_data.n_variables, lambda_=10, mu=10, budget=1000, x0=initial_pop)
CMA = modcma.ModularCMAES(fitness_func=f, parameters=params)

/Users/ernestvmo/Documents/VS Code Repo/ModularCMAES/modcma/parameters.py:433: RuntimeWarning: invalid value encountered in scalar divide
  mueff_neg = self.nweights.sum() ** 2 / (self.nweights ** 2).sum()
/Users/ernestvmo/Documents/VS Code Repo/ModularCMAES/modcma/parameters.py:446: RuntimeWarning: divide by zero encountered in scalar divide
  min(amu_neg, amueff_neg, aposdef_neg) / np.abs(self.nweights).sum()
/Users/ernestvmo/Documents/VS Code Repo/ModularCMAES/modcma/parameters.py:465: RuntimeWarning: invalid value encountered in sqrt
  2.0 * max(0.0, np.sqrt((self.mueff - 1) / (self.d + 1)) - 1) + self.cs


In [7]:
CMA.parameters.x0

array([[ 1.65295784],
       [-4.17532663],
       [-4.29109666],
       [-0.56129481],
       [-2.83043699]])

In [8]:
f.state

<State evaluations: 0 optimum_found: false current_best: <Solution x: [nan, nan, nan, nan, nan] y: inf>>

In [9]:
for i in range(10000):
    CMA.step()

In [10]:
f.state

<State evaluations: 100000 optimum_found: false current_best: <Solution x: [-0.4975258094342275, -0.04092740515708182, 4.92285265323851, 2.3187371677297612, 1.7770288571231536] y: 1976.3413574340766>>

In [11]:
CMA._fitness_func.state

<State evaluations: 100000 optimum_found: false current_best: <Solution x: [-0.4975258094342275, -0.04092740515708182, 4.92285265323851, 2.3187371677297612, 1.7770288571231536] y: 1976.3413574340766>>

In [12]:
CMA.parameters.population.x.shape

(5, 10)

In [13]:
CMA.parameters.population.x

array([[ 8.17374314e+00,  8.05549639e+00,  7.91588409e+00,
         7.77694303e+00,  7.58813787e+00,  7.59116957e+00,
         7.52397835e+00,  7.12948503e+00,  6.89736731e+00,
         6.52897016e+00],
       [-1.05647930e+00, -1.16664135e+00, -1.22625919e+00,
        -1.29863830e+00, -1.42841859e+00, -1.39583148e+00,
        -1.45875606e+00, -1.66995302e+00, -1.83995997e+00,
        -2.04621591e+00],
       [ 2.24888190e+00,  1.26866354e+00,  1.96895687e-03,
        -1.21826114e+00, -2.83159604e+00, -2.86839255e+00,
        -3.41056861e+00, -6.89946347e+00, -8.86113587e+00,
        -1.21034810e+01],
       [ 1.39813033e+00,  4.13449727e+00,  7.55041584e+00,
         1.08715049e+01,  1.53113605e+01,  1.53573844e+01,
         1.68804970e+01,  2.63700682e+01,  3.17899725e+01,
         4.06261020e+01],
       [-8.52988679e-01,  4.74702656e+00,  1.16656325e+01,
         1.84057407e+01,  2.74468444e+01,  2.75102775e+01,
         3.06285738e+01,  4.98919664e+01,  6.09394899e+01,
         7.

In [14]:
CMA.parameters.xopt, CMA.parameters.fopt, f(CMA.parameters.xopt)

(array([-0.49752581, -0.04092741,  4.92285265,  2.31873717,  1.77702886]),
 1976.3413574340766,
 1976.3413574340766)